[package]
name = "operating_system"
version = "0.1.0"
edition = "2021"
author = "ziggybaz"
aided_by = "Phillip Opperman"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
