[package]
name = "operating_system"
version = "0.1.0"
edition = "2021"
author = "ziggybaz"
aided_by = "Philipp Oppermann"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
